Retry body extraction if we receive documentElement is null error
When remote browser (chrome, firefox) are loading the page and we are trying to get document body - we encounter an error that `document.documentElement` is null. Page is not fully loaded yet. Most often this happens
on refreshing the page or when page is loaded by async JS code.

In order to recover from this - we wait 10 seconds for html/body then trying again or raising error

Example of error trace:

```
  1) Capybara::Session selenium_firefox_remote #refresh it reposts
     Failure/Error: browser.page_source

     Selenium::WebDriver::Error::JavascriptError:
       TypeError: document.documentElement is null
     # @http://127.0.0.1:42429/form:2:20
     # @http://127.0.0.1:42429/form:3:8
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium_statistics-0.3.0/lib/selenium_statistics/bridge.rb:14:in `execute'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:305:in `execute_script'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:116:in `page_source'
     # ./vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:160:in `page_source'
     # ./lib/capybara/selenium/driver.rb:87:in `html'
     # ./lib/capybara/session.rb:195:in `html'
     # ./lib/capybara/spec/spec_helper.rb:122:in `extract_results'
     # ./lib/capybara/spec/session/refresh_spec.rb:31:in `block (3 levels) in <top (required)>'
     # ./lib/capybara/spec/session/refresh_spec.rb:28:in `block (2 levels) in <top (required)>'
```